### ISSUE TITLE
jekyll serve Conversion error

### ISSUE THREAD

**Issue by ondergur** [riebeekn/jekyll-bootstrap-4-minimal-starter#1]
Hi. i just clone the repo and just try "jekyll serve" command. It just gave an error like this:
```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    Invalid CSS after "...lor}: #{$value}": expected "{", was ";" on line 4
jekyll 3.0.1 | Error:  Invalid CSS after "...lor}: #{$value}": expected "{", was ";" on line 4
```

**Comment by riebeekn** [comment]
Could be the Jekyll version, I was on 3.7.3 and just upgraded to 3.8.3, both of which work... Maybe do a "gem update jekyll" and see if that resolves things for you.
