### ISSUE TITLE
Getting ERROR `/css/main.css' not found

### ISSUE THREAD

**Issue by stefanocdn** [riebeekn/jekyll-bootstrap-4-minimal-starter#2]
Hi, after cloning the project I get ERROR `/css/main.css' not found
Any idea why?
Thank you

**Comment by riebeekn** [comment]
I gave it a go and didn't run into that error, only thing I can think of is maybe a jekyll version issue?  I am on version 3.8.3.

**Comment by stefanocdn** [comment]
Actually I have the same conversion error #1 
Running Jekyll 3.8.3 as well.
Any idea?

**Comment by riebeekn** [comment]
Unfortunately I don't have any ideas.  I installed ruby and jekyll on a clean Mac OS VM, cloned the repo and ran jekyll s... no errors popped up.

**Comment by stefanocdn** [comment]
It works when running `jekyll new` generator without passing the --blank flag.
Maybe related to the jekyll-sass-converter gem, and it not being present when running with --blank..
Thank you anyways!
